[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
clearwatch = "FDMGN1Gp62gK1TAnVvq2DM4HV6BhFwJ9Me5djLVKEKgB"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
